#!/usr/bin/env bash
#Install nginx web server
sudo apt update
sudo apt install nginx -y

#create index file
sudo touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

sudo sed -i "/server_name _;/ a rewrite ^/redirect_me https://flask.palletsprojects.com/en/2.0.x/ permanent;" /etc/nginx/sites-available/default

#restar the server
sudo service nginx restart

