#!/usr/bin/env bash
#This script use for loop print strings
END=100
for ((i=1;i<=END;i++))
do
	if [[ $((i%3)) == 0 && $((i%5)) == 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $((i%3)) == 0 ]]
	then
		echo "Fizz"
	elif [[ $((i%5)) == 0 ]]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done

