#!/usr/bin/env bash
#This script use while loop anf if, elif and else print strings
while ((i<10)); do
	if [[ "$i" == 3 ]]
	then
		echo "bad luck"
	elif [[ "$i" == 7 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done

