#!/usr/bin/env bash
#This script use while loop anf if, elif and else print strings
while ((i<20))
do
	echo "$((i+1))"
	case $i in
		3)	
			echo "bad luck from China"
		;;
		7)
			echo "bad luck from Japan"
		;;
		16)
			echo "bad luck from Italy"
		;;
	esac
	((i++))
done

