#!/usr/bin/env bash
#Run Nginx as Nginx

#stop service apache on port 8080
sudo pkill apache2

#change port of nginx
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default 

#give permissión to nginx user in nginx config file
sudo chmod 644 /etc/nginx/nginx.conf

#start service nginx as nginx user
sudo -u nginx service nginx start

